# Generated by Django 3.0.7 on 2020-07-20 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200721_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='customer',
            new_name='user',
        ),
    ]
