# Generated by Django 3.0.7 on 2020-07-22 00:16

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200721_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Eg +234, +233', max_length=128, null=True, region=None),
        ),
    ]
