# Generated by Django 3.0.7 on 2020-07-22 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200722_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='owner',
            new_name='user',
        ),
    ]
