# Generated by Django 3.0.7 on 2020-07-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200719_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='ref_code',
            field=models.CharField(default='47tiVz1URNKOwGao_NJwsSEVNs1GfXIBvbWNlE0nIMo', max_length=250),
        ),
    ]
