# Generated by Django 3.0.7 on 2020-07-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_cart_ref_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='ref_code',
            field=models.CharField(blank=True, default='jKVLdFXWkc83HfWOmEClJ-TrxT9d07g4l1r1Aih8g9Q', max_length=250, unique=True),
        ),
    ]
