# Generated by Django 3.0.7 on 2020-07-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200719_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='ref_code',
            field=models.CharField(blank=True, default='nMDE__-4HDx9gVnwclFeeVfD3Ajvb45vb1TLXzRMkpg', max_length=250, unique=True),
        ),
    ]
