# Generated by Django 3.0.7 on 2020-07-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200719_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='ref_code',
            field=models.CharField(blank=True, default='7-g-6mg0CcFIFSkCgJrJ5G8mJlrOcjlYK7iC1R-1Ej8', max_length=250, unique=True),
        ),
    ]
