# Generated by Django 3.0.7 on 2020-07-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200719_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='ref_code',
            field=models.CharField(blank=True, default='ger7R7EApE_y-FdjtblDqFd6m3VQtpQRR2kC31c0O88', max_length=250, unique=True),
        ),
    ]
