# Generated by Django 3.0.7 on 2020-07-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200719_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='ref_code',
            field=models.CharField(blank=True, default='fORrDbEJqRGJio8BW_E2yj1DLnzsZ85hNlx-_bOkzn8', max_length=250, unique=True),
        ),
    ]
