# Generated by Django 3.0.7 on 2020-07-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200719_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='ref_code',
            field=models.CharField(blank=True, default='HEXRzBgnI5Fz55WA-_w3LRA2_C70KWnlP13j0SdvSs4', max_length=250, unique=True),
        ),
    ]
