# Generated by Django 3.0.7 on 2020-07-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200719_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='ref_code',
            field=models.CharField(blank=True, default='xt2Ft-X173sB9y2xeVFbJGj-C1C2-ogeORSaIX9DWZ0', max_length=250, unique=True),
        ),
    ]
