# Generated by Django 3.0.7 on 2020-07-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200719_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='product',
            new_name='products',
        ),
        migrations.AlterField(
            model_name='cart',
            name='ref_code',
            field=models.CharField(blank=True, default='e_MRLIAzzeIWlm92wvOkZvALVgxFYDWIThpKekxqRxo', max_length=250, unique=True),
        ),
    ]
