# Generated by Django 3.0.7 on 2020-07-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200720_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='products',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='cart',
            name='ref_code',
            field=models.CharField(blank=True, default='RDf4YXMSf0Y56uiW6vh8gtu8FOtsuSNRbqjKKCTNqFw', max_length=250, unique=True),
        ),
    ]
