# Generated by Django 3.0.7 on 2020-07-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20200721_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(blank=True, default='0kDP4aR_tHT_memF_rju_EAydE1-0xfgB_sKcLiLoGM', max_length=250, unique=True),
        ),
    ]
