# Generated by Django 3.0.7 on 2020-07-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20200721_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(blank=True, default='q656t9EbBiR8_nO7TZfCc0MPDfgt5KaqTs20iKYiBjQ', max_length=250, unique=True),
        ),
    ]
