# Generated by Django 3.0.7 on 2020-07-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20200721_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(blank=True, default='0mFNZ-5nCCnUTZCUdch9iqx1LhKF7BsdNEYaREpf9RI', max_length=250, unique=True),
        ),
    ]
