# Generated by Django 3.0.7 on 2020-07-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20200721_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(blank=True, default='2lFGncxJtH4lDxYIULpbp1E0Xo-3nLd2T6A_3vkEIT4', max_length=250, unique=True),
        ),
    ]
