# Generated by Django 3.0.7 on 2020-07-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200717_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='images/product/no-image.jpg', upload_to='images/product/')),
                ('description', models.TextField(blank=True, default='No description')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ManyToManyField(to='products.ProductImage'),
        ),
    ]
